### ISSUE TITLE
Configuration file does not work

### ISSUE THREAD

**Issue by OPCUArules** [mtconnect/open62541_ua_server#7]
Hello,
I tried to run the software with 3 MTConnect Servers.
However, the interpretation of the configuration file goes completely wrong.
See attached Screenshots.
Since my config file is basically a copy of the sample file, I do not understand what to do.
regards

![ConfigurationFile](https://user-images.githubusercontent.com/61241824/74849548-1fcd2200-5339-11ea-9b5d-c59048a6f6b3.PNG)
![WrongReadingOfConfigurationFile](https://user-images.githubusercontent.com/61241824/74849550-2065b880-5339-11ea-8a72-14e74060335d.PNG)

**Comment by simonyg** [comment]
Any line starting with '#' should be ignored. You may have a hidden character before '#'. 

Suggestion: It is a comment line anyway. Remove this line and try it again.

**Comment by OPCUArules** [comment]
Hello,
thanks for your reply. I allready used the stable build.

By now I found the cause of the problem:
Apparently the file encoding was wrong. Copy and paste from the website lead to the problem.
Downloading and modifiing the original example.cfg file runs without problems.

Best regards

**Comment by simonyg** [comment]
Glad that you get it working.
