### ISSUE TITLE
Testing?

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/open62541_ua_server#9]
Hi, 
Does this application go through any Unit Test cases?
Has anyone used this application in Production yet?

Thanks

**Comment by simonyg** [comment]
Tests were run to ensure the consistency of results between MTConnect Agents and the UA server. Additionally, memory leak and endurance runs were performed. Even so, everyone is encouraged to perform your own testing in your environment.

**Comment by hulinning2** [comment]
Hi Simonyg, 
Do you have the test code stored on Git too?

Thanks

**Comment by simonyg** [comment]
They are not part of this repo. There are several components in the test:

1. Simulate MTConnect Agent with known publish data. Refer to https://github.com/mtconnect/cppagent_dev on how to run MTConnect agent with simulated data.
2. Connect OPC UA server to #1. Dump the content from this OPC UA server.
3. Verify the data between #1 and #2 (simulated data vs dump) to be the same.
